### PR TITLE
picking community `ambassador id` helm fix from master to include in release/v2.3

### PR DESCRIPTION
**Pull request by LanceEa**
## Description
This cherry-picks the community PR that was already merged into master so that it is included in the release/v2.3 branch.

## Related Issues
see #4199  for more details

## Testing
see #4199  for more details
## Checklist
 - [x] I made sure to update `CHANGELOG.md`. 
_Yes, community member already did this._
 - [x] This is unlikely to impact how Ambassador performs at scale.
 - [x] My change is adequately tested.
 - [x] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.
     _No changes were needed_
 - [x] The changes in this PR have been reviewed for security concerns and adherence to security best practices.

### CODE REVIEW

**Comment by LanceEa** [comment]
Ok...ignore something went wrong with my cherry pick

**Review by LukeShu — DISMISSED** [review]
Please use the `-x` flag to `git cherry-pick` to make it easy to trace this back to the original commit.

**Comment by LanceEa** [comment]
@LukeShu - done, I wasn't aware of that flag so thanks!

**Review by AliceProxy — APPROVED** [review]
Ignore that failed gotest, the specific failure is a known flake that has nothing to do with this PR and I'll verify that I saw this turn green before. Thanks for cherry-picking this into rel/2.3, lets get it in.

**Pull request merged**
