### PR TITLE
Emissary watch for CloudConnectToken ConfigMap or Secret 

### PR DESCRIPTION
**Pull request by alexgervais**
## Description
Emissary will now watch for ConfigMap or Secret resources specified by the `AGENT_CONFIG_RESOURCE_NAME` environment variable in order to allow all components (and not only the Ambassador Agent) to authenticate requests to Ambassador Cloud.

Notes for reviewers: I could not fully execute `make generate`, but my intention was to:
- Add RBAC permissions to get, list and watch `configmaps`.
- Add the `AGENT_CONFIG_RESOURCE_NAME` environment variable to the emissary deployment.
- Add a release note entry.

Let me know if I need to generate/synchronize anything else between Helm charts and YAML and changlog.

## Related Issues
None

## Testing
Manual tests

## Checklist

 - [x] I made sure to update `CHANGELOG.md`.
   
   Remember, the CHANGELOG needs to mention:
    + Any new features
    + Any changes to our included version of Envoy
    + Any non-backward-compatible changes
    + Any deprecations
 
 - [ ] This is unlikely to impact how Ambassador performs at scale.
 
   Remember, things that might have an impact at scale include:
    + Any significant changes in memory use that might require adjusting the memory limits
    + Any significant changes in CPU use that might require adjusting the CPU limits
    + Anything that might change how many replicas users should use
    + Changes that impact data-plane latency/scalability
 
 - [x] My change is adequately tested.
 
   Remember when considering testing:
    + Your change needs to be specifically covered by tests.
       + Tests need to cover all the states where your change is relevant: for example, if you add a behavior that can be enabled or disabled, you'll need tests that cover the enabled case and tests that cover the disabled case. It's not sufficient just to test with the behavior enabled.
    + You also need to make sure that the _entire area being changed_ has adequate test coverage.
       + If existing tests don't actually cover the entire area being changed, add tests.
       + This applies even for aspects of the area that you're not changing – check the test coverage, and improve it if needed!
    + We should lean on the bulk of code being covered by unit tests, but...
    + ... an end-to-end test should cover the integration points
 
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.

### CODE REVIEW

**Review by LukeShu — APPROVED** [review]
It would make sense to me if we wanted to stick the `secretRef(…)` call inside of the `if isEdgeStack { … }` block, and stick `, ignoreIf: !IsEdgeStack()` on the interesting_types entry.

But I have no strong opinion on the matter.

**Comment by LukeShu** [comment]
It looks like you need to
1. Run `make generate-fast`
2. Teach `cmd/entrypoint/testutil_fake_k8s_store_test.go:canonGVK()` about ConfigMaps.

**Review by LukeShu — CHANGES_REQUESTED** [review]
It looks like you need to
1. Run `make generate-fast`
2. Teach `cmd/entrypoint/testutil_fake_k8s_store_test.go:canonGVK()` about ConfigMaps.

**Comment by alexgervais** [comment]
> It would make sense to me if we wanted to stick the `secretRef(…)` call inside of the `if isEdgeStack { … }` block, and stick `, ignoreIf: !IsEdgeStack()` on the interesting_types entry.

I thought about this, and while it's true the current use case for watching this ConfigMap is to support an Edge Stack feature, the Cloud Connect Token is something all components (Emissary, Emissary-agent) might care about in the future.

**Review by LukeShu — APPROVED** [review]
Whoops, I thought I approved this once you got `make generate` working.

Hit it!

**Pull request merged**
