### PR TITLE
Updated documentation to avoid unnecessary changes to ClientConfig

### PR DESCRIPTION
**Pull request by aosoriodw**
## Description
Documented that `NewClientFromConfigFlags` should be used when more control over the client settings is needed.

## Testing
Not required

## Checklist

 - [ ] I made sure to update `CHANGELOG.md`.

   Remember, the CHANGELOG needs to mention:
    + Any new features
    + Any changes to our included version of Envoy
    + Any non-backward-compatible changes
    + Any deprecations

 - [x] This is unlikely to impact how Ambassador performs at scale.

   Remember, things that might have an impact at scale include:
    + Any significant changes in memory use that might require adjusting the memory limits
    + Any significant changes in CPU use that might require adjusting the CPU limits
    + Anything that might change how many replicas users should use
    + Changes that impact data-plane latency/scalability

 - [ ] My change is adequately tested.

   Remember when considering testing:
    + Your change needs to be specifically covered by tests.
       + Tests need to cover all the states where your change is relevant: for example, if you add a behavior that can be enabled or disabled, you'll need tests that cover the enabled case and tests that cover the disabled case. It's not sufficient just to test with the behavior enabled.
    + You also need to make sure that the _entire area being changed_ has adequate test coverage.
       + If existing tests don't actually cover the entire area being changed, add tests.
       + This applies even for aspects of the area that you're not changing – check the test coverage, and improve it if needed!
    + We should lean on the bulk of code being covered by unit tests, but...
    + ... an end-to-end test should cover the integration points

 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.

 - [x] The changes in this PR have been reviewed for security concerns and adherence to security best practices.

### CODE REVIEW

**Comment by rhs** [comment]
FYI Kates already supports impersonating users and groups. If you use `k8s.NewKubeInfoFromFlags` to construct your client then you will automatically get all the common boilerplate options that kubectl supports, including the impersonation flags. I'd recommend using that pattern rather than wiring up each flag one by one just because there are a lot of those flags and the set keeps growing as client-go evolves. See here for an example of how to do that: https://github.com/emissary-ingress/emissary/blob/9e8c3ec0fee5c878cba7410a3a62f861862683ff/cmd/kubestatus/main.go#L26

**Comment by rhs** [comment]
Just to be clear that's not a comment on this PR. The ClientConfig struct exists as it does because a) I didn't know about the generic client options portion of client-go when I wrote it and b) it's a reasonable convenience for a common case. I think it's reasonable to extend that convenience to include impersonation, the only other thing I'd suggest might be useful is to update the docs for ClientConfig to include a pointer to `k8s.NewKubeInfoFromFlags` along with a suggestion that if you're finding a need for some of the fancy options, then you probably just want to switch to that instead of using ClientConfig.

**Review by rhs — CHANGES_REQUESTED** [review]
Looks good to me, the only change I'd suggest is updating the documentation as I mentioned in my earlier comment.

**Comment by aosoriodw** [comment]
Agree that it's better to use `NewClientFromConfigFlags` when more control over the client configuration is needed. I've dropped the changes since they are not necessary and I have updated the documentation.

**Comment by haq204** [comment]
@aosoriodw changes look fine to me. but looks like the DCO check is failing so you will need to add a `Signed-off-by: ` to your commit.

**Review by LanceEa — APPROVED** [review]

**Comment by LanceEa** [comment]
Just needs the DCO, you will need to sign-off your commit. You can run `git commit --amend --signoff ` to amend the last commit and add sign-off signature.

**Pull request closed without merging**
