### PR TITLE
Update module.yaml

### LINKED ISSUE #4872: Chart 8.5.0  spec.ambassador_id in body must be of type array: "string"
**Describe the bug**
The helm chart 8.5.0 is invalid.

❯ helm upgrade test-ambassador datawire/emissary-ingress --version 8.5.0 -f values.yaml -n test

Error: UPGRADE FAILED: failed to create resource: Module.getambassador.io "ambassador" is invalid: spec.ambassador_id: Invalid value: "string": spec.ambassador_id in body must be of type array: "string"

In commit https://github.com/emissary-ingress/emissary/commit/8ca5a6f461a4629c5d4578c15e4816419e22088f
there has been an update from `getambassador.io/v2` to `getambassador.io/v3alpha1`.

But in v3alpha1:
```
ambassador_id:
    description: "AmbassadorID declares which Ambassador instances should
      pay attention to this resource. If no value is provided, the default
      is: \n \tambassador_id: \t- \"default\" \n TODO(lukeshu): In v3alpha2,
      consider renaming all of the `ambassador_id` (singular) fields to
      `ambassador_ids` (plural)."
    items:
      type: string
    type: array
```
this field now is an array, not a single field anymore.

**Expected behavior**
It should not fail.

**Versions**
 - Chart 8.5.0
 - Every kubernetes version supported

### PR DESCRIPTION
**Pull request by pie-r**
Fix #4872

## Description

Chart 8.5.0 is updating the api version from `getambassador.io/v2` to `getambassador.io/v3alpha1`

## Related Issues

#4872

## Testing

A few sentences describing what testing you've done, e.g., manual tests, automated tests, deployed in production, etc.

## Checklist

- [ ] **Does my change need to be backported to a previous release?**
  - What backport versions were discussed with the Maintainers in the Issue?

- [ ] **I made sure to update `CHANGELOG.md`.**

   Remember, the CHANGELOG needs to mention:
  - Any new features
  - Any changes to our included version of Envoy
  - Any non-backward-compatible changes
  - Any deprecations

- [x] **This is unlikely to impact how Ambassador performs at scale.**

   Remember, things that might have an impact at scale include:
  - Any significant changes in memory use that might require adjusting the memory limits
  - Any significant changes in CPU use that might require adjusting the CPU limits
  - Anything that might change how many replicas users should use
  - Changes that impact data-plane latency/scalability

- [x] **My change is adequately tested.**

   Remember when considering testing:
  - Your change needs to be specifically covered by tests.
    - Tests need to cover all the states where your change is relevant: for example, if you add a behavior that can be enabled or disabled, you'll need tests that cover the enabled case and tests that cover the disabled case. It's not sufficient just to test with the behavior enabled.
  - You also need to make sure that the _entire area being changed_ has adequate test coverage.
    - If existing tests don't actually cover the entire area being changed, add tests.
    - This applies even for aspects of the area that you're not changing – check the test coverage, and improve it if needed!
  - We should lean on the bulk of code being covered by unit tests, but...
  - ... an end-to-end test should cover the integration points

- [ ] **I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.**

- [ ] **The changes in this PR have been reviewed for security concerns and adherence to security best practices.**

### CODE REVIEW

**Review by haq204 — APPROVED** [review]
Opened https://github.com/emissary-ingress/emissary/pull/4874 to run CI. Thanks for catching this!

**Comment by pie-r** [comment]
thanks @haq204.
Just to know, my PR now is correct and is following the contribution rules?

**Comment by haq204** [comment]
> thanks @haq204. Just to know, my PR now is correct and is following the contribution rules?

@pie-r yea typically the main requirement is that your commits are signed. This is a CNCF thing. That is why I originally cherry-picked your commit on my PR branch. I have now rebased so things are a good. 

We're working on allowing CI run on community contributions (currently there is a permissions issue in our CI that prevents this) so hopefully we will be able to get that enabled soon.

Once CI is green in #4874 we should be good to go.

**Comment by pie-r** [comment]
ok thanks!

**Pull request closed without merging**
