### PR TITLE
Use environment variables to configure healthcheck server

### PR DESCRIPTION
**Pull request by TimonOmsk**
Signed-off-by: Dmitry Golushko <dmitry.golushko@veeam.com>

## Description

Full description and motivation can be found here:  https://github.com/emissary-ingress/emissary/issues/4274 

I decided to make it flexible and keep backward compatibility. 
I introduced 3 new environment variables:
|  Name | Description  | Default value  | Possible values | 
|---|---|---|---|
|  AMBASSADOR_HEALTHCHECK_BIND_ADDRESS |  allows to configure bind address for healthcheck server |  0.0.0.0 |  Any valid IPV4 or IPV6 address  |
|  AMBASSADOR_HEALTHCHECK_BIND_PORT |  allows to configure port for healthcheckserver | 8877  | Any valid port value  |
|  AMBASSADOR_HEALTHCHECK_IP_FAMILY |  allows to configure prefered IP family(IPV4, IPV6 or both) | ANY  | IPV4_ONLY, IPV6_ONLY, ANY  |

As I already described in the feature request in case of any wildcard IP(0.0.0.0, :: or just empty string) golang will try to bind to all available interface. Even if you specified IPV4 address (0.0.0.0) and host system is properly configured to use IPV4 mapped IPV6 address it will bind to IPV6 socket. To allow explicitly set preferred IP family the AMBASSADOR_HEALTHCHECK_IP_FAMILY was introduced. 

## Related Issues
https://github.com/emissary-ingress/emissary/issues/4274 

## Testing
A few sentences describing what testing you've done, e.g., manual tests, automated tests, deployed in production, etc.

## Checklist

 - [ ] I made sure to update `CHANGELOG.md`.

   Remember, the CHANGELOG needs to mention:
    + Any new features
    + Any changes to our included version of Envoy
    + Any non-backward-compatible changes
    + Any deprecations

 - [x] This is unlikely to impact how Ambassador performs at scale.

   Remember, things that might have an impact at scale include:
    + Any significant changes in memory use that might require adjusting the memory limits
    + Any significant changes in CPU use that might require adjusting the CPU limits
    + Anything that might change how many replicas users should use
    + Changes that impact data-plane latency/scalability

 - [ ] My change is adequately tested.

   Remember when considering testing:
    + Your change needs to be specifically covered by tests.
       + Tests need to cover all the states where your change is relevant: for example, if you add a behavior that can be enabled or disabled, you'll need tests that cover the enabled case and tests that cover the disabled case. It's not sufficient just to test with the behavior enabled.
    + You also need to make sure that the _entire area being changed_ has adequate test coverage.
       + If existing tests don't actually cover the entire area being changed, add tests.
       + This applies even for aspects of the area that you're not changing – check the test coverage, and improve it if needed!
    + We should lean on the bulk of code being covered by unit tests, but...
    + ... an end-to-end test should cover the integration points

 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.

 - [ ] The changes in this PR have been reviewed for security concerns and adherence to security best practices.

### CODE REVIEW

**Comment by ddymko** [comment]
@TimonOmsk hey there 👋 

I started looking at your PR and testing it. Would you be able to rebase PR off of master?

**Comment by TimonOmsk** [comment]
@ddymko hi!

Great news. I've resolved conflict.

**Comment by ddymko** [comment]
@TimonOmsk thanks for taking care of that!

I'll spend some time testing this out if all goes well then we will get this worked into the v3.2.0 release

**Comment by TimonOmsk** [comment]
@ddymko Great. Feel free to reach me in the Ambassador Labs Community Slack chat if you'd have any questions. I'm in CEST time zone(GMT+2)

**Pull request closed without merging**
