### PR TITLE
add support for a new knative ingress annotation

### PR DESCRIPTION
**Pull request by dprotaso**
## Description

Upstream in Knative I'm looking to make our annotations have consistent style & casing. This change introduces the ability for ambassador to recognize the new ingress annotation that'll be introduced a later date. 

## Related Issues
List related issues.

## Testing

Running tests was asking for root so I'm opting to letting the CI do it.

## Checklist

 - [X] This is unlikely to impact how Ambassador performs at scale.
 - [X] My change is adequately tested.

### CODE REVIEW

**Comment by dprotaso** [comment]
This should be good now

**Comment by kivo360** [comment]
What's the status on this one? I've really wanted to use Knative, but I've run into heavy issues with the notion. I just can't properly get the system running. It's compounded with the reality that I struggle to route resources to whatever resources do work.

**Comment by dprotaso** [comment]
@kivo360 this PR doesn't fix anything but just makes the emissary controller recognize a 'new' annotation key.

If you're having issues I'd suggesting filing a bug report here: https://github.com/emissary-ingress/emissary/issues/new?assignees=&labels=&template=Bug_report.md

**Comment by dprotaso** [comment]
cc @kflynn

**Pull request closed without merging**
