### PR TITLE
feat(helm): autoscaling - allow setting behaviors for HPA

### PR DESCRIPTION
**Pull request by eevdev**
## Description

Allow setting autoscaling/HorizontalPodAutoscaler (HPA) behaviors in chart.

Example Helm values:
```yaml
autoscaling:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - periodSeconds: 60
          type: Pods
          value: 1
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
        - periodSeconds: 60
          type: Pods
          value: 1
```

## Related Issues

#5217

## Testing

Manually tested.

## Checklist

- [ ] **Does my change need to be backported to a previous release?**
  - What backport versions were discussed with the Maintainers in the Issue?

- [x] **I made sure to update `CHANGELOG.md`.**

   Remember, the CHANGELOG needs to mention:
  - Any new features
  - Any changes to our included version of Envoy
  - Any non-backward-compatible changes
  - Any deprecations

- [x] **This is unlikely to impact how Ambassador performs at scale.**

   Remember, things that might have an impact at scale include:
  - Any significant changes in memory use that might require adjusting the memory limits
  - Any significant changes in CPU use that might require adjusting the CPU limits
  - Anything that might change how many replicas users should use
  - Changes that impact data-plane latency/scalability

- [ ] **My change is adequately tested.**

   Remember when considering testing:
  - Your change needs to be specifically covered by tests.
    - Tests need to cover all the states where your change is relevant: for example, if you add a behavior that can be enabled or disabled, you'll need tests that cover the enabled case and tests that cover the disabled case. It's not sufficient just to test with the behavior enabled.
  - You also need to make sure that the _entire area being changed_ has adequate test coverage.
    - If existing tests don't actually cover the entire area being changed, add tests.
    - This applies even for aspects of the area that you're not changing – check the test coverage, and improve it if needed!
  - We should lean on the bulk of code being covered by unit tests, but...
  - ... an end-to-end test should cover the integration points

- [ ] **I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.**

- [ ] **The changes in this PR have been reviewed for security concerns and adherence to security best practices.**

### CODE REVIEW

**Comment by LanceEa** [comment]
@eevdev - Can you please rebase on master to fix the changelog? I will then get CI running.

**Comment by eevdev** [comment]
> @eevdev - Can you please rebase on master to fix the changelog? I will then get CI running.

Done, although I guess I'll have to do it again when/if my other PRs are merged (#5220, #5221, #5223) as they're also adding to the changelog. Let me know if you have a nice way around that 😅

**Comment by LanceEa** [comment]
> They're also adding to the changelog. Let me know if you have a nice way around that 

It's a pain, you can either drop them and we can add the change log notes after the fact. We review the change log and tidy it up as needed before releases anways. Alternatively, you can stack them so that each one is based off each other but this has the downside that if the first pr needs fixed then it cascades.

**Review by LanceEa — APPROVED** [review]

**Review by haq204 — APPROVED** [review]

**Comment by eevdev** [comment]
I should say I included a fix for wrong apiVersion of HPA when deployed on EKS in this PR, which I believe should have fixed #5240.

03a32471a3bd2652770660abe141de2f4627d8db

**Pull request merged**
