### PR TITLE
charts: add tolerations, nodeSelector, affinity to agent

### PR DESCRIPTION
**Pull request by ppanyukov**
## Description

Resolves https://github.com/emissary-ingress/emissary/issues/4255. Now it's possible to specify standard things for the agent deployment too:

* tolerations
* affinity
* nodeSelector

## Related Issues

* https://github.com/emissary-ingress/emissary/issues/4255

## Testing

* Tested `tolerations` and `nodeSelector` with Helm chart v8.5.0 and now it deploys fine onto the required nodes.
* The `affinity` is not tested but it's a copy paste from `deployment.yaml` so I guess it should work too :)

## Checklist

- [ ] **Does my change need to be backported to a previous release?**
  - What backport versions were discussed with the Maintainers in the Issue?

- [ ] **I made sure to update `CHANGELOG.md`.**

   Remember, the CHANGELOG needs to mention:
  - Any new features
  - Any changes to our included version of Envoy
  - Any non-backward-compatible changes
  - Any deprecations

- [ ] **This is unlikely to impact how Ambassador performs at scale.**

   Remember, things that might have an impact at scale include:
  - Any significant changes in memory use that might require adjusting the memory limits
  - Any significant changes in CPU use that might require adjusting the CPU limits
  - Anything that might change how many replicas users should use
  - Changes that impact data-plane latency/scalability

- [ ] **My change is adequately tested.**

   Remember when considering testing:
  - Your change needs to be specifically covered by tests.
    - Tests need to cover all the states where your change is relevant: for example, if you add a behavior that can be enabled or disabled, you'll need tests that cover the enabled case and tests that cover the disabled case. It's not sufficient just to test with the behavior enabled.
  - You also need to make sure that the _entire area being changed_ has adequate test coverage.
    - If existing tests don't actually cover the entire area being changed, add tests.
    - This applies even for aspects of the area that you're not changing – check the test coverage, and improve it if needed!
  - We should lean on the bulk of code being covered by unit tests, but...
  - ... an end-to-end test should cover the integration points

- [ ] **I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.**

- [ ] **The changes in this PR have been reviewed for security concerns and adherence to security best practices.**

### CODE REVIEW

**Comment by alexgervais** [comment]
Huge thanks for your contribution @ppanyukov! Please make sure you sign (and re-push) your commits for the DCO check to pass. See https://github.com/emissary-ingress/emissary/pull/4880/checks?check_run_id=11580180076 for details.

Once merged, we should consider also updating the standalone [ambassador-agent.git](https://github.com/datawire/ambassador-agent) chart with a replicate of this change.

**Comment by ppanyukov-poq** [comment]
Hello @alexgervais I **think** I fixed the DCO issue, hopefully in the fight way! Of course there are other CI workflows that are not green, guess because this is a fork. Happy to try fix those too if I can and if required.

**Comment by ppanyukov** [comment]
Hello @alexgervais I **think** I fixed the DCO issue, hopefully in the right way! Of course there are other CI workflows that are not green, guess because this is a fork. Happy to try fix those too if I can and if required.

**Comment by LanceEa** [comment]
@ppanyukov - Thanks for the PR. Yeah, are CI needs some refactoring so that it is friendlier to non-maintainers. In the meantime, I have pulled in your changes, rebased on the latest master and triggered CI here: #4917.

**Comment by LanceEa** [comment]
@ppanyukov - I have gone ahead and rebased and added a changelog entry and pushed it to CI. Its running now and once green, I will get the other maintainers to review it so we can get it merged.

Thanks for the patience!

**Comment by LanceEa** [comment]
@ppanyukov - this has been merged via https://github.com/emissary-ingress/emissary/pull/4917. Thanks so much for the contribution and the patience!

**Pull request closed without merging**
