### PR TITLE
[v2.3.1] Release PR

### PR DESCRIPTION
**Pull request by AliceProxy**

### CODE REVIEW

**Comment by LanceEa** [comment]
@AliceProxy @LukeShu - what was the outcome of the make chart-test failing, I believe we understood why but unsure.

**Comment by AliceProxy** [comment]
> @AliceProxy @LukeShu - what was the outcome of the make chart-test failing, I believe we understood why but unsure. 

I believe Luke can better explain, but If the tag for a release is pushed  before the CRDs are made available then it will fail.

**Review by LanceEa — APPROVED** [review]
lgtm, since this already is released. The only up question for me is what do we need to do to address the chart check. Is there anything we need to do or just merge?

**Comment by LukeShu** [comment]
I expect the chart check to fail on a commit that has been tagged as an RC.

**Pull request merged**
